spring:
  application:
    name: sassfnb
  datasource:
    url: jdbc:postgresql://localhost:5432/sassfnb
    username: sassfnb
    password: devpass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: HikariPoolSassFnb
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: taikhoanduynhatkhongaigiong@gmail.com
    password: eqzy petd ndnd kfai
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app: # <-- ra ngoài spring
  jwt:
    secret: "supersecretjwtkeysassfnbforinternproject12345sassfnb"
    access-token-minutes: 60
    refresh-token-days: 14
  mail:
    from: taikhoanduynhatkhongaigiong@gmail.com
    verify-link-base: # hoặc FE URL
  email:
    verify-expire-minutes: 30
  urls:
    public-base: "http://localhost:8080"
    frontend-base: "http://localhost:5173"
  nuuls:
    apiBase: "https://i.nuuls.com/v1"
    apiKey: "29077f962f6787cf47e32225ab5d96ef"

  upload:
    provider: nuuls
    # localDir: uploads # thư mục trên máy
    # publicBase: http://localhost:8080/files/
  qr:
    publicRedirectBase: http://localhost:5173/order
    staticSecret: change-me-super-secret
  dev:
    defaults:
      tenantId: "00000000-0000-0000-0000-000000000001"
      restaurantId: "a2211f37-a786-4a17-9a26-fdc2e2103c67"
      outletId: "765ad55f-2c08-4a71-a846-11b0d8587c41"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.sassfnb.config.jwt: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
